### ISSUE TITLE
Strange Interaction with Exchangers and Faction Mod

### ISSUE THREAD

**Issue by Akitori** [mffbrokenswing/FactionMod#2] opened 2017-12-31 06:51 UTC
https://github.com/JackyyTV/Exchangers/issues/41 

I originally reported it there but I'll repeat here.

Using exchangers near faction claimed land causes a strange issue, to the point of being to duplicate blocks. (seen here)

https://youtu.be/AvLs45PitBY

The modmaker told me to report it here, so here i am.

**Comment by BrokenSwing** [comment] 2018-01-01 17:31
I can't fix it by my side (the only thing my mod does is canceling Forge events when a player places/breaks blocks).  It's really weird, because, if you look into Exchangers mod's code, blocks should be replaced correctly. The only thing I could notice is the mod author doesn't fire any Forge event when the player replace blocks, so we can't cancel it. A ``BreakEvent`` or a ``PlaceEvent`` could maybe be fired here : https://github.com/JackyyTV/Exchangers/blob/dev-1.12/src/main/java/jackyy/exchangers/handler/ExchangerHandler.java#L196

**Comment by JackyyTV** [comment] 2018-01-02 03:09
Hey there, I am the dev for Exchangers, currently trying to fix this problem on my side. Just wondering if this is the right way I should put my `PlaceEvent` in.
```Java
BlockEvent.PlaceEvent event = new BlockEvent.PlaceEvent(new BlockSnapshot(world, coordinate, block.getStateFromMeta(meta)), oldState, player, null);
if (!event.isCanceled()) {
    if (consumeItemInInventory(Item.getItemFromBlock(block), meta, player.inventory, player)) {
        //Exchanger replace blocks codes goes here
    }
}
```

**Comment by BrokenSwing** [comment] 2018-01-02 09:16
Ok, I found where is the bug coming from. When the players uses the exchanger, Forge fires the event ``MultiPlaceEvent`` which heritates from ``PlaceEvent`` so my mod cancels it and blocks aren't placed but as you don't get notified blocks aren't placed, you gives items to the player. I did this code, it should be nice to re-organize it I think : 
```java
 Set<BlockPos> coordinates = findSuitableBlocks(stack, world, side, pos, oldblock, oldmeta);
        boolean notEnough = false;
        for (BlockPos coordinate : coordinates) {
            if (consumeItemInInventory(Item.getItemFromBlock(block), meta, player.inventory, player)) {
                BreakEvent bEvent = new BreakEvent(world, coordinate, world.getBlockState(coordinate), player);
                if (!MinecraftForge.EVENT_BUS.post(bEvent)) {
                    PlaceEvent event = new PlaceEvent(new BlockSnapshot(world, coordinate, block.getStateFromMeta(meta)), Blocks.AIR.getDefaultState(), player, player.getActiveHand());
                    if (!MinecraftForge.EVENT_BUS.post(event)) {
                        world.playSound(null, coordinate.getX(), coordinate.getY(), coordinate.getZ(), SoundEvents.ENTITY_ENDERMEN_TELEPORT,
                                SoundCategory.BLOCKS, 0.1F, 1F);
                        world.captureBlockSnapshots = false;
                        world.setBlockState(coordinate, block.getStateFromMeta(meta), 3);
                        world.captureBlockSnapshots = true;

                        if (!player.capabilities.isCreativeMode && !isCreative()) {
                            ItemStack oldblockItem = oldblock.getItem(world, coordinate, oldState);
                            giveItem(world, player, pos, oldblockItem);
                            if (!isPowered() && !isCreative()) {
                                stack.damageItem(1, player);
                            } else if (stack.getTagCompound().getInteger("Energy") >= getPerBlockUse()) {
                                stack.getTagCompound().setInteger("Energy", stack.getTagCompound().getInteger("Energy") - getPerBlockUse());
                            }
                        }
                    } else {
                        giveItem(world, player, pos, new ItemStack(block, 1, meta));
                    }
                } else {
                    giveItem(world, player, pos, new ItemStack(block, 1, meta));
                }
                player.openContainer.detectAndSendChanges();
            } else {
                notEnough = true;
            }
        }
```

**Comment by BrokenSwing** [comment] 2018-01-02 09:17
I didn't test it, so it could not work. And now I look back to the code, ``BreakEvent`` is useless.

**Comment by JackyyTV** [comment] 2018-01-02 10:24
I see what the differences are now. So I should be using `if (!MinecraftForge.EVENT_BUS.post(event))` instead of `if (!event.isCanceled())` right? So it should be like this:
```Java
for (BlockPos coordinate : coordinates) {
    BlockEvent.PlaceEvent event = new BlockEvent.PlaceEvent(new BlockSnapshot(world, coordinate, block.getStateFromMeta(meta)), oldState, player, null);
    if (!MinecraftForge.EVENT_BUS.post(event)) {
        if (consumeItemInInventory(Item.getItemFromBlock(block), meta, player.inventory, player)) {
            //Exchanger replace blocks codes goes here
        }
    }
}
```
I think I am gonna add a warning chat message on my side about the event being cancelled as well if the operation fails.

**Comment by BrokenSwing** [comment] 2018-01-02 11:04
Uhmm ... I miss-unerstood the way PlaceEvent works, you have to place the block, fire the event and restore the block if the event is canceled : 

```java
    // We don't want world to capture blockSnapchot as we're doing it ourself
    world.captureBlockSnapshots = false;
    
    // We prepare the event
    PlaceEvent placeEvent = new PlaceEvent(BlockSnapshot.getBlockSnapshot(world, pos, 3), Blocks.AIR.getDefaultState(), player, hand);
    
    // We set the block in the world
    world.setBlockState(pos, block.getStateFromMeta(meta), 3);
    
    // We set back field to true
    world.captureBlockSnapshots = true;
    
    // We post the event on Forge's event bus and check if the event is canceled
    if(MinecraftForge.EVENT_BUS.post(placeEvent)) {
        
        // If the event is canceled we restore the BlockSnapshot
        placeEvent.getBlockSnapshot().restore(true);
    } else {
        // Else the block is placed and we can do more stuff
    }
```

**Comment by JackyyTV** [comment] 2018-01-02 12:15
Alright, I see, so that is the correct way I should handle the event.

**Comment by JackyyTV** [comment] 2018-01-02 12:29
We're getting somewhere I guess...
```Java
for (BlockPos coordinate : coordinates) {
    world.captureBlockSnapshots = false;
    BlockEvent.PlaceEvent event = new BlockEvent.PlaceEvent(BlockSnapshot.getBlockSnapshot(world, coordinate, 3), Blocks.AIR.getDefaultState(), player, null);
    world.setBlockState(coordinate, block.getStateFromMeta(meta), 3);
    world.captureBlockSnapshots = true;
    if (!MinecraftForge.EVENT_BUS.post(event)) {
        if (consumeItemInInventory(Item.getItemFromBlock(block), meta, player.inventory, player)) {
            //Event is not cancelled
        }
     } else {
        //Event is cancelled
        event.getBlockSnapshot().restore(true);
    }
}
```

**Comment by BrokenSwing** [comment] 2018-01-02 12:49
Yes, and don't forget to change the null paramater, it's annotated with ``Nonnull`` so you should put ``player.getActiveHand()`` instead of ``null``.
```java
for (BlockPos coordinate : coordinates) {
    world.captureBlockSnapshots = false;
    BlockEvent.PlaceEvent event = new BlockEvent.PlaceEvent(BlockSnapshot.getBlockSnapshot(world, coordinate, 3), Blocks.AIR.getDefaultState(), player, player.getActiveHand());
    world.setBlockState(coordinate, block.getStateFromMeta(meta), 3);
    world.captureBlockSnapshots = true;
    if (!MinecraftForge.EVENT_BUS.post(event) && consumeItemInInventory(Item.getItemFromBlock(block), meta, player.inventory, player)) {
            //Event is not cancelled
            // play sound, give replaced block to player, consume energy
     } else {
        //Event is cancelled or player hasn't the required block in his inventory
        event.getBlockSnapshot().restore(true);
    }
}
```

**Comment by JackyyTV** [comment] 2018-01-02 12:51
Oh, I was working on that on the 1.10.2 version and the EnumHand param is annotated as `@Nullable`, fixed now.

**Comment by BrokenSwing** [comment] 2018-01-02 13:19
My bad then 😃 Tell me if it fixes things, then I close the issue.

**Comment by JackyyTV** [comment] 2018-01-02 13:20
Yeah, I shall port the changes to 1.11 and 1.12 first, then hand over a 1.12 jar for @Akitori to test it.

**Comment by Akitori** [comment] 2018-01-02 16:02
oh okay.

**Comment by JackyyTV** [comment] 2018-01-05 02:58
New issue happened...
Apparently the exchange event did get cancelled, but it still managed to exchange some blocks, not quite sure why that happened.
https://github.com/JackyyTV/Exchangers/issues/41#issuecomment-355363302

**Comment by BrokenSwing** [comment] 2018-01-05 09:40
Can you post here the new code ? It seems like ``BlockSnapshot#restore`` didn't work

**Comment by JackyyTV** [comment] 2018-01-05 10:22
This is the [new code](https://github.com/JackyyTV/Exchangers/blob/dev-1.11.2/src/main/java/jackyy/exchangers/handler/ExchangerHandler.java#L194-L232) (I know it's 1.11 but it's basicially the same as 1.12 and I haven't updated the 1.12 codes yet).

**Comment by BrokenSwing** [comment] 2018-01-05 10:22
I found where is the bug coming from, when restoring the ``BlockSnapshot`` we still capturing them (see ``world.captureBlockSnapshots = true`` when we're restoring, so the block is captured and Forge fires an event, my mod cancels this event, and Forge restores the block (without capturing). Here is the new code which could work : 
```java
world.captureBlockSnapshots = false;
for (BlockPos coordinate : coordinates) {
    BlockEvent.PlaceEvent event = new BlockEvent.PlaceEvent(BlockSnapshot.getBlockSnapshot(world, coordinate, 3), Blocks.AIR.getDefaultState(), player, player.getActiveHand());
    world.setBlockState(coordinate, block.getStateFromMeta(meta), 3);
    if (!MinecraftForge.EVENT_BUS.post(event) && consumeItemInInventory(Item.getItemFromBlock(block), meta, player.inventory, player)) {
            //Event is not cancelled
            // play sound, give replaced block to player, consume energy
     } else {
        //Event is cancelled or player hasn't the required block in his inventory
        world.restoringBlockSnapshots = true;
        event.getBlockSnapshot().restore(true);
        world.restoringBlockSnapshots = false;
    }
}
world.captureBlockSnapshots = true;
```

**Comment by JackyyTV** [comment] 2018-01-05 10:24
Ah right, I shall change that and see if it's fixed.

**Comment by JackyyTV** [comment] 2018-01-05 21:54
This bug is confirmed being fixed after those changes. Thanks for the help @MFFbrokenSwing, much appreciated. ❤️

**Comment by BrokenSwing** [comment] 2018-01-06 11:06
You're welcome

**Closed as completed by BrokenSwing** 2018-01-06 11:06 UTC
Labels: bug, compatibility
